### ISSUE TITLE
Input from the bubble

### ISSUE THREAD

**Issue by pabrcno** [KohlsAdrian/bubble_overlay#10]
Hi! Thanks for creating something awesome!. My issue is that I need to receive some input from the bubble, for example when the user taps it adds 1 to a counter. Can it be done?

**Comment by alejandrogiubel** [comment]
@pabrcno How you solved this?

**Comment by pabrcno** [comment]
I used another approach. Input from notifications, It is not as good as I was planning to do with the bubble overlay but it is good enough.  
https://pub.dev/packages/awesome_notifications
Here is a tutorial for it:
https://www.youtube.com/watch?v=JAq9fVn3X7U&t=1958s

**Comment by alejandrogiubel** [comment]
Thank
