### ISSUE TITLE
Add video playback

### ISSUE THREAD

**Issue by Frank0945** [KohlsAdrian/bubble_overlay#2]
If we can put the video inside, it will be perfect.  Come on!

**Comment by KohlsAdrian** [comment]
![Screenshot_2020-07-17-22-42-30-838_com.adriankohls.bubble_overlay_example.jpg](https://user-images.githubusercontent.com/6604704/87841851-d4cf2080-c87e-11ea-9915-86c7f7e0e8f2.jpg)

Feature request on the way

Just some small adjustments still

**Comment by KohlsAdrian** [comment]
[This](https://github.com/KohlsAdrian/bubble_overlay/commit/f1dff177715d0917279a040181df9aa44e1158e6) commit added support.
Already available on pub.dev
