### ISSUE TITLE
Video cannot be displayed

### ISSUE THREAD

**Issue by Frank0945** [KohlsAdrian/bubble_overlay#3]
Other functions are behaving normally, but the video cannot be displayed.

![](https://i.imgur.com/5jg5PiD.jpg)

What the debug console shows when I press "Open Bubble Video".

`D/ViewRootImpl@1c25c51[MainActivity]( 9751): ViewPostIme pointer 0
D/ViewRootImpl@1c25c51[MainActivity]( 9751): ViewPostIme pointer 1
D/ViewRootImpl@1c25c51[MainActivity]( 9751): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 9751): prepareNavigationBarInfo() DecorView@7db17d5[MainActivity]
D/InputMethodManager( 9751): getNavigationBarColor() -855310
D/ViewRootImpl@1c25c51[MainActivity]( 9751): setWindowStopped(true) old=false
D/SurfaceView( 9751): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{f882cb6 V.E...... ........ 0,0-1080,2076} of ViewRootImpl@1c25c51[MainActivity]
D/SurfaceView( 9751): show() Surface(name=SurfaceView - com.example.pipTest/com.example.pipTest.MainActivity@f882cb6@26[9751])/@0x8f29c09 io.flutter.embedding.android.FlutterSurfaceView{f882cb6 V.E...... ........ 0,0-1080,2076}
D/SurfaceView( 9751): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{f882cb6 V.E...... ........ 0,0-1080,2076}
W/libEGL  ( 9751): EGLNativeWindowType 0x7667daf010 disconnect failed
D/SurfaceView( 9751): destroy() Surface(name=SurfaceView - com.example.pipTest/com.example.pipTest.MainActivity@f882cb6@26[9751])/@0x8f29c09 io.flutter.embedding.android.FlutterSurfaceView{f882cb6 V.E...... ........ 0,0-1080,2076}
D/SurfaceView( 9751): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{f882cb6 V.E...... ........ 0,0-1080,2076} of ViewRootImpl@1c25c51[MainActivity]
W/libEGL  ( 9751): EGLNativeWindowType 0x7640bf0010 disconnect failed
D/OpenGLRenderer( 9751): eglDestroySurface = 0x7677e97e80, 0x7640bf0000
D/ViewRootImpl@1c25c51[MainActivity]( 9751): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={valid=false 0} changed=true
D/InputTransport( 9751): Input channel destroyed: fd=128
D/ViewRootImpl@1c25c51[MainActivity]( 9751): Surface release. android.view.ViewRootImpl$ViewRootHandler.handleMessage:4825 android.os.Handler.dispatchMessage:106
D/SurfaceView( 9751): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{f882cb6 V.E...... ........ 0,0-1080,2076} of ViewRootImpl@1c25c51[MainActivity]
D/ViewRootImpl@1c25c51[MainActivity]( 9751): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=false 0} changed=false
`

**Comment by KohlsAdrian** [comment]
Plaease show your AndroidManifest.xml

**Comment by Frank0945** [comment]
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.pipTest">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="pipTest"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
        >
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <service
            android:name="com.adriankohls.bubble_overlay.BubbleOverlayService"
            android:enabled="true"
            android:exported="false" />
        <service
            android:name="com.adriankohls.BubbleVideoOverlayService.BubbleOverlayService"
            android:enabled="true"
            android:exported="false" />
    </application>
</manifest>
`

**Comment by KohlsAdrian** [comment]
replace

      <service
        android:name="com.adriankohls.BubbleVideoOverlayService.BubbleOverlayService"
        android:enabled="true"
        android:exported="false" />
with

      <service
        android:name="com.adriankohls.bubble_overlay.BubbleVideoOverlayService.BubbleOverlayService"
        android:enabled="true"
        android:exported="false" />

**Comment by KohlsAdrian** [comment]
replace
    
    <service
        android:name="com.adriankohls.BubbleVideoOverlayService.BubbleOverlayService"
        android:enabled="true"
        android:exported="false" />

for

      <service
        android:name="com.adriankohls.bubble_overlay.BubbleVideoOverlayService"
        android:enabled="true"
        android:exported="false" />

checkout the example/ folder more details!

**Comment by KohlsAdrian** [comment]
Your service declaration is different from the example

https://github.com/KohlsAdrian/bubble_overlay/blob/master/example/android/app/src/main/AndroidManifest.xml

**Comment by Frank0945** [comment]
Oh! Thanks.
It's okay now.

I just copy README, so i didn't notice the difference.

**Comment by KohlsAdrian** [comment]
Fixing readme on next git push
