### ISSUE TITLE
[Feature] Add support for Offline videos

### ISSUE THREAD

**Issue by rehamalraee** [KohlsAdrian/bubble_overlay#4]
Currently the package dose not support playing videos from local path (uploaded to the project) .
it is only support videos over the internet .
Is there any way to play local video ?

**Comment by KohlsAdrian** [comment]
In the next release of bubble_overlay, it will get and easy way to read offline Media Files to play.

At the moment you can try converting the asset file to ByteData and converting to File object and it will get the platform-path to read the file.

@rehamalraee use this snippet while the feature is not yet implemented: 

    void openBubbleVideoAssets() async {
        String asset = 'assets/video.mp4';
        ByteData data = await rootBundle.load(asset);
        List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
        Directory directory = await getApplicationDocumentsDirectory();
        String dbPath = join(directory.path, 'video.mp4');
        File file = await File(dbPath).writeAsBytes(bytes);
        String uri = file.path;
        bubbleOverlay.openVideoBubble(uri);
    }

Replace the "asset" String with the file you want to use. This snippet is ready2go

**Comment by KohlsAdrian** [comment]
Released on pub.dev

[Commit address](https://github.com/KohlsAdrian/bubble_overlay/commit/5ada58bef8727ab155ddac88ac7b19ef69f4aa62)

**Comment by rehamalraee** [comment]
@KohlsAdrian Not Working !!

**Comment by rehamalraee** [comment]
![ssssssssssss](https://user-images.githubusercontent.com/71270985/93332629-c8d5ef80-f82a-11ea-9314-8bf9e9f07dc3.PNG)

**Comment by rehamalraee** [comment]
@KohlsAdrian  after implementing the snippet above I've got this error Unable to load asset: assets/...
