### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Not allowed to start service Intent { 

### ISSUE THREAD

**Issue by rehamalraee** [KohlsAdrian/bubble_overlay#7]
Hello , this error shows up after calling video bubble for the second time , always !
can any one help ?? please
![feesfefwe](https://user-images.githubusercontent.com/71270985/96330934-d1a42600-1061-11eb-8fec-f356731b2623.PNG)

**Comment by rehamalraee** [comment]
bubbleOverlay.openVideoBubble(assets,controlsType: ControlsType.STANDARD);
Im Using this to call and the assets is path file in phone storage

**Comment by KohlsAdrian** [comment]
Hi, I am little busy at the moment
Please provide the code you are using in flutter

And what is "assets" and its content

**Comment by rehamalraee** [comment]
@KohlsAdrian  hello Adrian 
I got that this exception appears after a time because my app is still in recent apps but  it is dummy, after minutes my flutter app becomes like a zombie that's why the bubble service can not start again.

**Comment by rehamalraee** [comment]
@KohlsAdrian  Hello Adrian, 
after wasting more than two weeks trying to fix this issue from my side(my app code) it seems it is a plugin's bug, it appears when calling openVideoBubble after leaving the app for minutes in recent apps without clicking it, or when moving between other apps for a very few minutes !! Please suggest what to do 
![tempsnip](https://user-images.githubusercontent.com/71270985/97865214-856c0d80-1d12-11eb-83ae-f75b4c051d67.png)

**Comment by rehamalraee** [comment]
**### **WHY I see this error when I see this when I send My app to background?**** 

by: java.lang.IllegalArgumentException: Service not registered: com.adriankohls.bubble_overlay.BubbleOverlayPlugin$connect$1@d761707
E/AndroidRuntime(32227): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1888)
E/AndroidRuntime(32227): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1835)
E/AndroidRuntime(32227): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:752)
E/AndroidRuntime(32227): 	at com.adriankohls.bubble_overlay.BubbleOverlayPlugin.release(BubbleOverlayPlugin.kt:162)
E/AndroidRuntime(32227): 	at com.adriankohls.bubble_overlay.BubbleOverlayPlugin.onDetachedFromEngine(BubbleOverlayPlugin.kt:262)
E/AndroidRuntime(32227): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime(32227): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime(32227): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:268)
E/AndroidRuntime(32227): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:112)
E/AndroidRuntime(32227): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:365)
E/AndroidRuntime(32227): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:528)
E/AndroidRuntime(32227): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime(32227): 	at android.app.Activity.performDestroy(Activity.java:8254)
E/AndroidRuntime(32227): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1341)
E/AndroidRuntime(32227): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5283)

**Comment by KohlsAdrian** [comment]
Please provide your app

 AndroidManifest.xml

**Comment by rehamalraee** [comment]
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.xxxxx.xx">
    
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_CALL_LOG"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"
                     android:maxSdkVersion="29"/>
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permissions.READ_PHONE_NUMBERS"/>
    <uses-permission android:name="android.permissions.BIND_INCALL_SERVICE"/>
    <application
            android:name=".App"
            android:label="vrbt"
            android:requestLegacyExternalStorage="true"
            android:icon="@mipmap/ic_launcher">
        <activity
                android:name=".MainActivity"
                android:launchMode="singleTop"
                android:usesCleartextTraffic="true"
                android:screenOrientation="portrait"
                android:theme="@style/LaunchTheme"
                android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                android:hardwareAccelerated="true"
                android:windowSoftInputMode="adjustResize">
            
            <meta-data
                    android:name="io.flutter.embedding.android.NormalTheme"
                    android:resource="@style/NormalTheme"
            />
            
            <meta-data
                    android:name="io.flutter.embedding.android.SplashScreenDrawable"
                    android:resource="@drawable/launch_background"
            />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        
        <meta-data
                android:name="flutterEmbedding"
                android:value="2" />
        <service
                android:name="com.adriankohls.bubble_overlay.BubbleOverlayService"
                android:enabled="true"
                android:exported="false" />
        <service
                android:name="com.adriankohls.bubble_overlay.BubbleVideoOverlayService"
                android:enabled="true"
                android:exported="false" />
        <service android:name="com.adriankohls.bubble_overlay.BReceiver"
                 android:directBootAware="true"
        />
        

        
        
        
        <service android:name=".MyService"
                 android:enabled="true"
                 android:exported="false"
                 android:directBootAware="true">
            
            
            
            
            
            
            
            
        </service>
        <service
                android:name=".SimpleJobIntentService"
                android:permission="android.permission.BIND_JOB_SERVICE" />
        <provider
                android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
                android:authorities="${applicationId}.flutter_downloader.provider"
                android:exported="false"
                android:grantUriPermissions="true">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/provider_paths"/>
        </provider>
        <receiver android:name=".autostart">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="android.intent.action.REBOOT"/>
            </intent-filter>
        </receiver>
        <receiver android:name=".CallService">
            <intent-filter>
                <action android:name="android.intent.action.PHONE_STATE" />
            </intent-filter>
        </receiver>
    </application>
</manifest>

**Comment by rehamalraee** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.xxxxx.xxx">
    
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_CALL_LOG"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"
                     android:maxSdkVersion="29"/>
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permissions.READ_PHONE_NUMBERS"/>
    <uses-permission android:name="android.permissions.BIND_INCALL_SERVICE"/>
    <application
            android:name=".App"
            android:label="xxxx"
            android:requestLegacyExternalStorage="true"
            android:icon="@mipmap/ic_launcher">
        <activity
                android:name=".MainActivity"
                android:launchMode="singleTop"
                android:usesCleartextTraffic="true"
                android:screenOrientation="portrait"
                android:theme="@style/LaunchTheme"
                android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                android:hardwareAccelerated="true"
                android:windowSoftInputMode="adjustResize">
            
            <meta-data
                    android:name="io.flutter.embedding.android.NormalTheme"
                    android:resource="@style/NormalTheme"
            />
            
            <meta-data
                    android:name="io.flutter.embedding.android.SplashScreenDrawable"
                    android:resource="@drawable/launch_background"
            />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        
        <meta-data
                android:name="flutterEmbedding"
                android:value="2" />
        <service
                android:name="com.adriankohls.bubble_overlay.BubbleOverlayService"
                android:enabled="true"
                android:exported="false" />
        <service
                android:name="com.adriankohls.bubble_overlay.BubbleVideoOverlayService"
                android:enabled="true"
                android:exported="false" />
       <service android:name=".MyService"
                 android:enabled="true"
                 android:exported="false"
                 android:directBootAware="true">
        </service>
        <provider
                android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
                android:authorities="${applicationId}.flutter_downloader.provider"
                android:exported="false"
                android:grantUriPermissions="true">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/provider_paths"/>
        </provider>
        <receiver android:name=".autostart">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="android.intent.action.REBOOT"/>
            </intent-filter>
        </receiver>
        <receiver android:name=".CallService">
            <intent-filter>
                <action android:name="android.intent.action.PHONE_STATE" />
            </intent-filter>
        </receiver>
    </application>
</manifest>

**Comment by KohlsAdrian** [comment]
So, you are trying to interact with the bubble service using your own service called "CallService" ?

**Comment by rehamalraee** [comment]
> So, you are trying to interact with the bubble service using your own service called "MyService"?

@KohlsAdrian I've tried yes, but the exception appears without that interaction, I played a video bubble from the plugin itself, then I closed the app so my service has to run.

**Comment by KohlsAdrian** [comment]
I need mlre detail's of what you are trying to achieve. I have no clue to tey to "fix"

**Comment by rehamalraee** [comment]
@KohlsAdrian  there is no relation between the exception and what I've tried to do, the exception appears with the simple use of the plugin!!

**Comment by KohlsAdrian** [comment]
What format of video you are trying to play on the plugin?
Does your phone has some battery saving mode? That may cause a killer app to save resources?
Are you using vanilla features on phone?

**Comment by rehamalraee** [comment]
1. video file from mobile storage 
2.No,all are disabled 
3.No.

**Comment by rehamalraee** [comment]
Not Solved, to get rid of this exception I  implemented the bubble overlay in native directly without using the plugin.
